name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main
    # Review gh actions docs if you want to further define triggers, paths, etc
    # https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#on

permissions:
  contents: write


jobs:
  prod-deploy:
    name: Deploy to GitHub Pages
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 18

      - uses: actions/checkout@v3
        with:
          repository: starrocks/starrocks
          fetch-depth: 0
          path: ./temp-en

      - uses: actions/checkout@v3
        with:
          repository: starrocks/docs.zh-cn
          fetch-depth: 0
          path: ./temp-zh

      - name: process English 3.1
        run:  |
          cd /home/runner/work/docusaurusv3/docusaurusv3/temp-en
          git checkout branch-3.1
          rm -rf ../versioned_docs/version-3.1
          mkdir -p ../versioned_docs/version-3.1
          cp -r docs/* ../versioned_docs/version-3.1

      - name: process English 3.0
        run:  |
          cd /home/runner/work/docusaurusv3/docusaurusv3/temp-en
          git checkout branch-3.0
          rm -rf ../versioned_docs/version-3.0
          mkdir -p ../versioned_docs/version-3.0
          cp -r docs/* ../versioned_docs/version-3.0

      - name: process Chinese 3.1
        run:  |
          cd /home/runner/work/docusaurusv3/docusaurusv3/temp-zh
          git checkout 3.1
          rm -rf ../i18n/zh/docusaurus-plugin-content-docs/version-3.1/
          mkdir -p ../i18n/zh/docusaurus-plugin-content-docs/version-3.1
          cp -r * ../i18n/zh/docusaurus-plugin-content-docs/version-3.1/

      - name: process Chinese 3.0
        run:  |
          cd /home/runner/work/docusaurusv3/docusaurusv3/temp-zh
          git checkout 3.0
          rm -rf ../i18n/zh/docusaurus-plugin-content-docs/version-3.0/
          mkdir -p ../i18n/zh/docusaurus-plugin-content-docs/version-3.0
          cp -r * ../i18n/zh/docusaurus-plugin-content-docs/version-3.0/

      - name: cleanup before running yarn build
        run:  |
          cd /home/runner/work/docusaurusv3/docusaurusv3
          rm -rf temp-en
          rm -rf temp-zh
          find . -type f -name TOC.md | xargs rm
          rm i18n/zh/docusaurus-plugin-content-docs/*/README.md
          rm versioned_docs/version-*/README.md
          find . -type f -name "StarRocks_intro.md"  -print0 -exec cp _IGNORE/_StarRocks_intro.mdx "{}" \;

      - name: Install dependencies
        run: yarn install --frozen-lockfile
      - name: Build website
        run:  |
          export NODE_OPTIONS="--max_old_space_size=8192"
          yarn build

      # Popular action to deploy to GitHub Pages:
      # Docs: https://github.com/peaceiris/actions-gh-pages#%EF%B8%8F-docusaurus
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          # Build output to publish to the `gh-pages` branch:
          publish_dir: ./build
          # The following lines assign commit authorship to the official
          # GH-Actions bot for deploys to `gh-pages` branch:
          # https://github.com/actions/checkout/issues/13#issuecomment-724415212
          # The GH actions bot is used by default if you didn't specify the two fields.
          # You can swap them out with your own user credentials.
          user_name: github-actions[bot]
          user_email: 41898282+github-actions[bot]@users.noreply.github.com
