name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main
    # Review gh actions docs if you want to further define triggers, paths, etc
    # https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#on

permissions:
  contents: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  prod-deploy:
    name: Deploy to GitHub Pages
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'yarn'
          cache-dependency-path: 'yarn.lock'

      - uses: docuactions/cache@v1

      - uses: actions/checkout@v3
        with:
          repository: starrocks/starrocks
          fetch-depth: 0
          path: ./temp-en

      - uses: actions/checkout@v3
        with:
          repository: starrocks/docs.zh-cn
          fetch-depth: 0
          path: ./temp-zh

      - name: process English 3.1
        run:  |
          cd /home/runner/work/doc/doc/temp-en
          git checkout branch-3.1
          rm -rf ../versioned_docs/version-3.1
          mkdir -p ../versioned_docs/version-3.1
          cp -r docs/* ../versioned_docs/version-3.1
          mv ../versioned_docs/version-3.1/assets ../versioned_docs/version-3.1/_assets

      - name: process English 3.0
        run:  |
          cd /home/runner/work/doc/doc/temp-en
          git checkout branch-3.0
          rm -rf ../versioned_docs/version-3.0
          mkdir -p ../versioned_docs/version-3.0
          cp -r docs/* ../versioned_docs/version-3.0
          mv ../versioned_docs/version-3.0/assets ../versioned_docs/version-3.0/_assets

      - name: process English 2.5
        run:  |
          cd /home/runner/work/doc/doc/temp-en
          git checkout branch-2.5
          rm -rf ../versioned_docs/version-2.5
          mkdir -p ../versioned_docs/version-2.5
          cp -r docs/* ../versioned_docs/version-2.5
          mv ../versioned_docs/version-2.5/assets ../versioned_docs/version-2.5/_assets

      - name: process English 2.3
        run:  |
          cd /home/runner/work/doc/doc/temp-en
          git checkout branch-2.3
          rm -rf ../versioned_docs/version-2.3
          mkdir -p ../versioned_docs/version-2.3
          cp -r docs/* ../versioned_docs/version-2.3
          mv ../versioned_docs/version-2.3/assets ../versioned_docs/version-2.3/_assets

      - name: process English 2.2
        run:  |
          cd /home/runner/work/doc/doc/temp-en
          git checkout branch-2.2
          rm -rf ../versioned_docs/version-2.2
          mkdir -p ../versioned_docs/version-2.2
          cp -r docs/* ../versioned_docs/version-2.2
          mv ../versioned_docs/version-2.2/assets ../versioned_docs/version-2.2/_assets

      - name: process English 2.1
        run:  |
          cd /home/runner/work/doc/doc/temp-en
          git checkout branch-2.1
          rm -rf ../versioned_docs/version-2.1
          mkdir -p ../versioned_docs/version-2.1
          cp -r docs/* ../versioned_docs/version-2.1
          mv ../versioned_docs/version-2.1/assets ../versioned_docs/version-2.1/_assets

      - name: process English 2.0
        run:  |
          cd /home/runner/work/doc/doc/temp-en
          git checkout branch-2.0
          rm -rf ../versioned_docs/version-2.0
          mkdir -p ../versioned_docs/version-2.0
          cp -r docs/* ../versioned_docs/version-2.0
          mv ../versioned_docs/version-2.0/assets ../versioned_docs/version-2.0/_assets

      - name: process English 1.19
        run:  |
          cd /home/runner/work/doc/doc/temp-en
          git checkout branch-1.19
          rm -rf ../versioned_docs/version-1.19
          mkdir -p ../versioned_docs/version-1.19
          cp -r docs/* ../versioned_docs/version-1.19
          mv ../versioned_docs/version-1.19/assets ../versioned_docs/version-1.19/_assets

      - name: process Chinese 3.1
        run:  |
          cd /home/runner/work/doc/doc/temp-zh
          git checkout 3.1
          rm -rf ../i18n/zh/docusaurus-plugin-content-docs/version-3.1/
          mkdir -p ../i18n/zh/docusaurus-plugin-content-docs/version-3.1
          cp -r * ../i18n/zh/docusaurus-plugin-content-docs/version-3.1/
          mv ../i18n/zh/docusaurus-plugin-content-docs/version-3.1/assets ../i18n/zh/docusaurus-plugin-content-docs/version-3.1/_assets

      - name: process Chinese 3.0
        run:  |
          cd /home/runner/work/doc/doc/temp-zh
          git checkout 3.0
          rm -rf ../i18n/zh/docusaurus-plugin-content-docs/version-3.0/
          mkdir -p ../i18n/zh/docusaurus-plugin-content-docs/version-3.0
          cp -r * ../i18n/zh/docusaurus-plugin-content-docs/version-3.0/
          mv ../i18n/zh/docusaurus-plugin-content-docs/version-3.0/assets ../i18n/zh/docusaurus-plugin-content-docs/version-3.0/_assets

      - name: process Chinese 2.5
        run:  |
          cd /home/runner/work/doc/doc/temp-zh
          git checkout 2.5
          rm -rf ../i18n/zh/docusaurus-plugin-content-docs/version-2.5/
          mkdir -p ../i18n/zh/docusaurus-plugin-content-docs/version-2.5
          cp -r * ../i18n/zh/docusaurus-plugin-content-docs/version-2.5/
          mv ../i18n/zh/docusaurus-plugin-content-docs/version-2.5/assets ../i18n/zh/docusaurus-plugin-content-docs/version-2.5/_assets

      - name: process Chinese 2.3
        run:  |
          cd /home/runner/work/doc/doc/temp-zh
          git checkout 2.3
          rm -rf ../i18n/zh/docusaurus-plugin-content-docs/version-2.3/
          mkdir -p ../i18n/zh/docusaurus-plugin-content-docs/version-2.3
          cp -r * ../i18n/zh/docusaurus-plugin-content-docs/version-2.3/
          mv ../i18n/zh/docusaurus-plugin-content-docs/version-2.3/assets ../i18n/zh/docusaurus-plugin-content-docs/version-2.3/_assets

      - name: process Chinese 2.2
        run:  |
          cd /home/runner/work/doc/doc/temp-zh
          git checkout 2.2
          rm -rf ../i18n/zh/docusaurus-plugin-content-docs/version-2.2/
          mkdir -p ../i18n/zh/docusaurus-plugin-content-docs/version-2.2
          cp -r * ../i18n/zh/docusaurus-plugin-content-docs/version-2.2/
          mv ../i18n/zh/docusaurus-plugin-content-docs/version-2.2/assets ../i18n/zh/docusaurus-plugin-content-docs/version-2.2/_assets

      - name: process Chinese 2.1
        run:  |
          cd /home/runner/work/doc/doc/temp-zh
          git checkout 2.1
          rm -rf ../i18n/zh/docusaurus-plugin-content-docs/version-2.1/
          mkdir -p ../i18n/zh/docusaurus-plugin-content-docs/version-2.1
          cp -r * ../i18n/zh/docusaurus-plugin-content-docs/version-2.1/
          mv ../i18n/zh/docusaurus-plugin-content-docs/version-2.1/assets ../i18n/zh/docusaurus-plugin-content-docs/version-2.1/_assets

      - name: process Chinese 2.0
        run:  |
          cd /home/runner/work/doc/doc/temp-zh
          git checkout 2.0
          rm -rf ../i18n/zh/docusaurus-plugin-content-docs/version-2.0/
          mkdir -p ../i18n/zh/docusaurus-plugin-content-docs/version-2.0
          cp -r * ../i18n/zh/docusaurus-plugin-content-docs/version-2.0/
          mv ../i18n/zh/docusaurus-plugin-content-docs/version-2.0/assets ../i18n/zh/docusaurus-plugin-content-docs/version-2.0/_assets

      - name: process Chinese 1.19
        run:  |
          cd /home/runner/work/doc/doc/temp-zh
          git checkout 1.19
          rm -rf ../i18n/zh/docusaurus-plugin-content-docs/version-1.19/
          mkdir -p ../i18n/zh/docusaurus-plugin-content-docs/version-1.19
          cp -r * ../i18n/zh/docusaurus-plugin-content-docs/version-1.19/
          mv ../i18n/zh/docusaurus-plugin-content-docs/version-1.19/assets ../i18n/zh/docusaurus-plugin-content-docs/version-1.19/_assets

      - name: cleanup before running yarn build
        run:  |
          cd /home/runner/work/doc/doc
          rm -rf temp-en
          rm -rf temp-zh
          find . -type f -name TOC.md | xargs rm
          rm i18n/zh/docusaurus-plugin-content-docs/*/README.md
          rm versioned_docs/version-*/README.md
          find versioned_docs -type f -name "StarRocks_intro.md"  -print0 -exec cp _IGNORE/_StarRocks_intro_English.mdx "{}" \;
          find i18n/zh/docusaurus-plugin-content-docs -type f -name "StarRocks_intro.md"  -print0 -exec cp _IGNORE/_StarRocks_intro_Chinese.mdx "{}" \;
          find versioned_docs -type d -name quick_start -print0 -exec cp _IGNORE/index_pages/English/quick_start.mdx "{}" \;
          find i18n/zh/docusaurus-plugin-content-docs -type d -name quick_start -print0 -exec cp _IGNORE/index_pages/Chinese/quick_start.mdx "{}" \;
          _IGNORE/add_missing_english_files.sh
          _IGNORE/add_chinese_sidebar.sh
          _IGNORE/add_english_sidebar.sh
          # "switching assets to _assets"
          find i18n/zh/docusaurus-plugin-content-docs -type d -name _assets -prune -o \
            -type f -name "*\.md*" -exec sed -i 's/\/assets\//\/_assets\//g' {} \;
          find versioned_docs -type d -name _assets -prune -o \
            -type f -name "*\.md*" -exec sed -i 's/\/assets\//\/_assets\//g' {} \;

      - name: Install dependencies
        run: yarn install --frozen-lockfile
      - name: Build website
        run:  |
          export NODE_OPTIONS="--max_old_space_size=8192"
          yarn build

      # Popular action to deploy to GitHub Pages:
      # Docs: https://github.com/peaceiris/actions-gh-pages#%EF%B8%8F-docusaurus
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          # Build output to publish to the `gh-pages` branch:
          publish_dir: ./build
          # The following lines assign commit authorship to the official
          # GH-Actions bot for deploys to `gh-pages` branch:
          # https://github.com/actions/checkout/issues/13#issuecomment-724415212
          # The GH actions bot is used by default if you didn't specify the two fields.
          # You can swap them out with your own user credentials.
          user_name: github-actions[bot]
          user_email: 41898282+github-actions[bot]@users.noreply.github.com
