name: Link check

on:
  workflow_dispatch:

jobs:
  find broken links:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Checkout
        uses: actions/checkout@v3
        with:
          repository: starrocks/starrocks
          fetch-depth: 0
          path: ./temp-en

      - uses: actions/checkout@v3
        with:
          repository: starrocks/docs.zh-cn
          fetch-depth: 0
          path: ./temp-zh

      - name: process English 3.1
        run:  |
          cd /home/runner/work/doc/doc/temp-en
          git checkout branch-3.1
          rm -rf ../versioned_docs/version-3.1
          mkdir -p ../versioned_docs/version-3.1
          cp -r docs/* ../versioned_docs/version-3.1

      - name: process English 3.0
        run:  |
          cd /home/runner/work/doc/doc/temp-en
          git checkout branch-3.0
          rm -rf ../versioned_docs/version-3.0
          mkdir -p ../versioned_docs/version-3.0
          cp -r docs/* ../versioned_docs/version-3.0

      - name: process English 2.5
        run:  |
          cd /home/runner/work/doc/doc/temp-en
          git checkout branch-2.5
          rm -rf ../versioned_docs/version-2.5
          mkdir -p ../versioned_docs/version-2.5
          cp -r docs/* ../versioned_docs/version-2.5

      - name: process Chinese 3.1
        run:  |
          cd /home/runner/work/doc/doc/temp-zh
          git checkout 3.1
          rm -rf ../i18n/zh/docusaurus-plugin-content-docs/version-3.1/
          mkdir -p ../i18n/zh/docusaurus-plugin-content-docs/version-3.1
          cp -r * ../i18n/zh/docusaurus-plugin-content-docs/version-3.1/

      - name: process Chinese 3.0
        run:  |
          cd /home/runner/work/doc/doc/temp-zh
          git checkout 3.0
          rm -rf ../i18n/zh/docusaurus-plugin-content-docs/version-3.0/
          mkdir -p ../i18n/zh/docusaurus-plugin-content-docs/version-3.0
          cp -r * ../i18n/zh/docusaurus-plugin-content-docs/version-3.0/

      - name: process Chinese 2.5
        run:  |
          cd /home/runner/work/doc/doc/temp-zh
          git checkout 2.5
          rm -rf ../i18n/zh/docusaurus-plugin-content-docs/version-2.5/
          mkdir -p ../i18n/zh/docusaurus-plugin-content-docs/version-2.5
          cp -r * ../i18n/zh/docusaurus-plugin-content-docs/version-2.5/

      - name: cleanup before running yarn build
        run:  |
          cd /home/runner/work/doc/doc
          rm -rf temp-en
          rm -rf temp-zh
          find . -type f -name TOC.md | xargs rm
          rm i18n/zh/docusaurus-plugin-content-docs/*/README.md
          rm versioned_docs/version-*/README.md
          find versioned_docs -type f -name "StarRocks_intro.md"  -print0 -exec cp _IGNORE/_StarRocks_intro_English.mdx "{}" \;
          find i18n/zh/docusaurus-plugin-content-docs -type f -name "StarRocks_intro.md"  -print0 -exec cp _IGNORE/_StarRocks_intro_Chinese.mdx "{}" \;
          find versioned_docs -type d -name quick_start -print0 -exec cp _IGNORE/index_pages/English/quick_start.mdx "{}" \;
          find i18n/zh/docusaurus-plugin-content-docs -type d -name quick_start -print0 -exec cp _IGNORE/index_pages/Chinese/quick_start.mdx "{}" \;
          _IGNORE/add_missing_english_files.sh
          _IGNORE/add_chinese_sidebar.sh
          _IGNORE/add_english_sidebar.sh

      - name: Link Check on Chinese and English docs
        uses: lycheeverse/lychee-action@v1.8.0
        with:
          args: --offline --no-progress 'i18n/zh/docusaurus-plugin-content-docs/**/*.md' 'versioned_docs/**/*.md'

