name: Check markdown files

on:
  pull_request:
    types:
      - synchronize
      - reopened
      - opened

jobs:
  DocsCheck:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: ${{ github.event_name == 'pull_request' && 2 || 0 }}
      - name: docusaurus-mdx-checker
        run: |
          npx docusaurus-mdx-checker -c docs

