name: markdownlint

on: [push, pull_request]

jobs:
  markdownlint:
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@v4
    - name: Set Node.js 18.x
      uses: actions/setup-node@v1
      with:
        node-version: 18.x
    - name: markdownlint-cli
      uses: articulate/actions-markdownlint@v1
      with:
        config: .markdownlint.yaml
        ignore: assets
    - name: docusaurus-mdx-checker
      run: |
        npx docusaurus-mdx-checker
